* g_lisp
- 增加一个新的小project，以后追踪我自己的lisp学习历程。
* happy hacking for lisp
* 维护者联系方式
- 微信： grey0612  添加时务必备注lisp并说明自己的沟通目的
- Email： greyzhang@126.com

* TODO 计划以及探索
** 概述
- 【尝试路线1】最初的学习，直接按照《实用common lisp编程》从头开始学习，感觉学习不顺利，从环境到教程都不算是适应，放弃。
- 【尝试路线2】教程依然是《实用common lisp编程》，放弃了lisp in a box的开发环境，采用clisp。教程太难，放弃。
- 【尝试路线3】算是精神胜利式的冲锋，再次回到路线1，最终感觉教程不适合我这样的初学者，放弃。
- 【尝试路线4】直接在实践中学习，上来就读代码，不懂的时候补充学习基础。学习对象从common lisp转换到了emacs lisp，学习的内容为spacemacs的配置。
** 环境搭建
*** lisp in a box
- 这个是common lisp的一个默认的开发环境，我看了下，到我查看的时候版本还没有出1.0，不知道是否意味着功能不健全或者不稳定？
- 这个环境是基于emacs的，重新从《实用common lisp编程》开始学习，还是回到了这个IDE。
*** clisp
- 这是我今天刚刚找到的一个新的开发环境，有着跟Perl或者Python解析器类似的使用方式。同时，也可以使用类似Python idle的REPL模式。
*** emacs
- 兜兜转转切换到了emacs，emacs本身其实带有一个lisp的环境。不过，这个lisp环境是elisp环境，也就是emacs lisp。
  学习common lisp的过程中遇到了太多的障碍，没有顺手的资料而已参考。切换到elisp，大致的lisp的思想应该可以体验到。
  同时，这个emacs内置的文档就已经比较丰富了，在家上elisp的官方文档，学习或许会更加顺利。学习的过程中，正好也可以
  进一步了解我现在依赖程度这么高的emacs编辑器。

** DONE 软件运行方法
   CLOSED: [2020-01-14 周二 22:44]
** DONE 文本文件处理
   CLOSED: [2020-01-14 周二 22:44]
** TODO 变量定义以及声明处理
- let以及let* --> OK
- 动态变量定义 --> OK
** DONE 函数设计
   CLOSED: [2020-01-14 周二 22:44]
** TODO 闭包
* 小练习
- common lisp开发环境与语言初步
N191， https://blog.csdn.net/grey_csdn/article/details/103691274
- 如何运行lisp代码
N192， https://blog.csdn.net/grey_csdn/article/details/103691528
- 文件句柄的使用
N193， https://blog.csdn.net/grey_csdn/article/details/103924724
- common lisp的几种函数定义
N194， https://blog.csdn.net/grey_csdn/article/details/103931418
- 变量定义之let以及let*
N195， https://blog.csdn.net/grey_csdn/article/details/103965807
- 动态变量定义
N196， https://blog.csdn.net/grey_csdn/article/details/103981189
- common lisp 内置的自增以及自减函数
N197， https://blog.csdn.net/grey_csdn/article/details/104012196
- emacs lisp: setq使用
N198， https://blog.csdn.net/grey_csdn/article/details/104158807
- emacs lisp: 常量定义探索
N199， https://blog.csdn.net/grey_csdn/article/details/104159540
- emacs版本高低判断
N200， https://blog.csdn.net/grey_csdn/article/details/104162177
- emacs lisp: 字符串拼接、字符串连接
N201， https://blog.csdn.net/grey_csdn/article/details/104167066
- emacs lisp: error提示
N202， https://blog.csdn.net/grey_csdn/article/details/104170167
- emacs lisp: 条件分支
N203， https://blog.csdn.net/grey_csdn/article/details/104171834
- emacs lisp: 与或非
N204， https://blog.csdn.net/grey_csdn/article/details/104174920
- emacs lisp: emacs加载文件的信息依据
N205， https://blog.csdn.net/grey_csdn/article/details/104175380
- emacs lisp: 根据文件全名获取文件所在目录信息
N206， https://blog.csdn.net/grey_csdn/article/details/104179658
- emacs lisp: emacs lisp文件加载
N207， https://blog.csdn.net/grey_csdn/article/details/104186184
- emacs lisp: 变量赋值之setq
N208， https://blog.csdn.net/grey_csdn/article/details/104221124
- emacs lisp: 向列表中增加不存在的元素
N209， https://blog.csdn.net/grey_csdn/article/details/104222122
- emacs lisp: 通过load加载文件以及函数搜索目录
N210， https://blog.csdn.net/grey_csdn/article/details/104222631
- emacs lisp: spacemacs增加load加载目录封装
N211， https://blog.csdn.net/grey_csdn/article/details/104223175
- emacs lisp: when条件分支
N212， https://blog.csdn.net/grey_csdn/article/details/104223675
- emacs lisp: emacs lisp判断文件是否存在
N213， https://blog.csdn.net/grey_csdn/article/details/104232723
- emacs lisp: spacemacs的用户目录
N214， https://blog.csdn.net/grey_csdn/article/details/104232950
- emacs lisp: 展开文件名为绝对目录格式
N215， https://blog.csdn.net/grey_csdn/article/details/104233439
- emacs lisp: spacemacs的目录定义
N216， https://blog.csdn.net/grey_csdn/article/details/104234583
- emacs lisp: 创建目录
N217， https://blog.csdn.net/grey_csdn/article/details/104234894
- emacs lisp: unless条件分支
N218， https://blog.csdn.net/grey_csdn/article/details/104236132
- emacs lisp: 反引号的作用
N221， https://blog.csdn.net/grey_csdn/article/details/104268436
- emacs lisp: car与cdr函数
N222， https://blog.csdn.net/grey_csdn/article/details/104268483
- emacs lisp: 映射类函数
N223， https://blog.csdn.net/grey_csdn/article/details/104268516
- emacs lisp: 用户主题搜索目录
N224， https://blog.csdn.net/grey_csdn/article/details/104268777
- emacs lisp: provide 以及 require函数使用
N225， https://blog.csdn.net/grey_csdn/article/details/104270387
- emacs lisp: 控制 *Message* buffer的log条目
N226， https://blog.csdn.net/grey_csdn/article/details/104270841
- emacs lisp: 获取当前的时间
N227， https://blog.csdn.net/grey_csdn/article/details/104286324
- spacemacs题外话: 增加几款备选主题
N229， https://blog.csdn.net/grey_csdn/article/details/104302524

