* g_lisp
- 增加一个新的小project，以后追踪我自己的lisp学习历程。
* happy hacking for lisp
* 维护者联系方式
- 微信： grey0612  添加时务必备注lisp并说明自己的沟通目的
- Email： greyzhang@126.com

* 环境搭建
*** lisp in a box
- 这个是common lisp的一个默认的开发环境，我看了下，到我查看的时候版本还没有出1.0，不知道是否意味着功能不健全或者不稳定？
- 这个环境是基于emacs的，重新从《实用common lisp编程》开始学习，还是回到了这个IDE。
*** clisp
- 这是我今天刚刚找到的一个新的开发环境，有着跟Perl或者Python解析器类似的使用方式。同时，也可以使用类似Python idle的REPL模式。
* TODO 计划以及探索
** 概述
- 【尝试路线1】最初的学习，直接按照《实用common lisp编程》从头开始学习，感觉学习不顺利，从环境到教程都不算是适应，放弃。
- 【尝试路线2】教程依然是《实用common lisp编程》，放弃了lisp in a box的开发环境，采用clisp。教程太难，放弃。
- 【尝试路线3】算是精神胜利式的冲锋，再次回到路线1，最终感觉教程不适合我这样的初学者，放弃。
- 【尝试路线4】直接在实践中学习，上来就读代码，不懂的时候补充学习基础。学习对象从common lisp转换到了emacs lisp，学习的内容为spacemacs的配置。
** DONE 开发环境搭建
   CLOSED: [2020-01-14 周二 22:44]
** DONE 软件运行方法
   CLOSED: [2020-01-14 周二 22:44]
** DONE 文本文件处理
   CLOSED: [2020-01-14 周二 22:44]
** TODO 变量定义以及声明处理
- let以及let* --> OK
- 动态变量定义 --> OK
** DONE 函数设计
   CLOSED: [2020-01-14 周二 22:44]
** TODO 闭包
* 小练习
- common lisp开发环境与语言初步
N191， https://blog.csdn.net/grey_csdn/article/details/103691274
- 如何运行lisp代码
N192， https://blog.csdn.net/grey_csdn/article/details/103691528
- 文件句柄的使用
N193， https://blog.csdn.net/grey_csdn/article/details/103924724
- common lisp的几种函数定义
N194， https://blog.csdn.net/grey_csdn/article/details/103931418
- 变量定义之let以及let*
N195， https://blog.csdn.net/grey_csdn/article/details/103965807
- 动态变量定义
N196， https://blog.csdn.net/grey_csdn/article/details/103981189
- common lisp 内置的自增以及自减函数
N197， https://blog.csdn.net/grey_csdn/article/details/104012196
- emacs lisp: setq使用
N198， https://blog.csdn.net/grey_csdn/article/details/104158807
- emacs lisp: 常量定义探索
N199， https://blog.csdn.net/grey_csdn/article/details/104159540
- emacs版本高低判断
N200， https://blog.csdn.net/grey_csdn/article/details/104162177
- emacs lisp: 字符串拼接、字符串连接
N201， https://blog.csdn.net/grey_csdn/article/details/104167066
- emacs lisp: error提示
N202， https://blog.csdn.net/grey_csdn/article/details/104170167
- emacs lisp: 条件分支
N203， https://blog.csdn.net/grey_csdn/article/details/104171834
- emacs lisp: 与或非
N204， https://blog.csdn.net/grey_csdn/article/details/104174920
- emacs lisp: emacs加载文件的信息依据
N205， https://blog.csdn.net/grey_csdn/article/details/104175380
- emacs lisp: 根据文件全名获取文件所在目录信息
N206， https://blog.csdn.net/grey_csdn/article/details/104179658
- emacs lisp: emacs lisp文件加载
N207， https://blog.csdn.net/grey_csdn/article/details/104186184
- emacs lisp: 变量赋值之setq
N208， https://blog.csdn.net/grey_csdn/article/details/104221124
- emacs lisp: 向列表中增加不存在的元素
N209， https://blog.csdn.net/grey_csdn/article/details/104222122

